### ISSUE TITLE
API spec in README.md is not match the current version '0.3.1' from npm.

### ISSUE THREAD

**Issue by Dafrok** [sketchglass/react-draggable-tree#24]
When I was using the current version(0.3.1) from npm, I found the interface named `rowContent` in neither source code nor compiled code, as the [index.d.ts](https://github.com/sketchglass/react-draggable-tree/blob/master/lib/index.d.ts) in master branch said.

**Comment by seanchas116** [comment]
Thanks! I changed the API in #21 but it had not been released to npm.
I released latest version as 0.4.0 now.

**Comment by Dafrok** [comment]
Thank you for your hard working!

**Comment by Dafrok** [comment]
It works perfect ❤️
